language: node_js
node_js:
  - "8"
services: mongodb
before_install:
    - cd server
before_script:
    - sleep 15
install:
    - npm install 
script:
    - cp .env-getting-started .env
    - npm run test-server
