version: "3.5"
services:
  server:
    build:
      context: .
      dockerfile: DockerfileServer
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: "npm run build-pm2"